### ISSUE TITLE
Time Requirements of Sampling Watermarked Dataset

### ISSUE THREAD

**Issue by skpig** [chenchenygu/watermark-learnability#3]
Thanks for the great work and resources!
I'm currently following your work. I wonder how much time is needed to generate these watermarked datasets (e.g. [this one](https://huggingface.co/datasets/cygu/sampling-distill-train-data-kgw-k0-gamma0.25-delta1))?

**Comment by chenchenygu** [comment]
On one A100 80GB, it should take somewhere around 30 hours to generate the full dataset.
